#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-webencodings
Version  : 0.5.1
Release  : 2
URL      : https://files.pythonhosted.org/packages/0b/02/ae6ceac1baeda530866a85075641cec12989bd8d31af6d5ab4a3e8c92f47/webencodings-0.5.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/0b/02/ae6ceac1baeda530866a85075641cec12989bd8d31af6d5ab4a3e8c92f47/webencodings-0.5.1.tar.gz
Summary  : Character encoding aliases for legacy web content
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-webencodings-python = %{version}-%{release}
Requires: pypi-webencodings-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
===================
        
        This is a Python implementation of the `WHATWG Encoding standard

%package python
Summary: python components for the pypi-webencodings package.
Group: Default
Requires: pypi-webencodings-python3 = %{version}-%{release}

%description python
python components for the pypi-webencodings package.


%package python3
Summary: python3 components for the pypi-webencodings package.
Group: Default
Requires: python3-core
Provides: pypi(webencodings)

%description python3
python3 components for the pypi-webencodings package.


%prep
%setup -q -n webencodings-0.5.1
cd %{_builddir}/webencodings-0.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649794737
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
